import assert from "node:assert/strict";
import test from "node:test";
import { MondayClient, assertReadOnlyQuery, dateCoverage, normalizeBoard, normalizePeople, normalizeStatus, parseMondayDate, redactToken, sampleItem, summarizeMonthlySalesBoard } from "../lib/monday/salesHistoryAudit.ts";
import { aggregateYear, classifyBoardPeriod, indexMonthlyBoards, parseMonthlyBoardName, validateMonthlyBoard } from "../lib/monday/monthlyBoardAudit.ts";

test("normalizes board, status, people, dates, and coverage deterministically", () => {
  assert.deepEqual(normalizeBoard({ id: "1", name: "Sales", state: "active", groups: [{ id: "g", title: "Inbox" }], columns: [{ id: "status", title: "Stage", type: "status" }], workspace: { id: "2", name: "Ops" } }).columns, [{ id: "status", title: "Stage", type: "status", settings: null }]);
  assert.equal(normalizeStatus(" Converted  "), "converted"); assert.deepEqual(normalizePeople('{"personsAndTeams":[{"id":12,"kind":"person"},{"id":99,"kind":"team"}]}'), [{ id: "12", name: "" }]); assert.equal(parseMondayDate("2024-02-03"), "2024-02-03");
  assert.deepEqual(dateCoverage([{ id: "1", name: "a", created_at: "2024-03-01" }, { id: "2", name: "b", created_at: null }]), { earliestUsableItemDate: "2024-03-01", latestUsableItemDate: "2024-03-01", datedItemCount: 1, undatedItemCount: 1 }); assert.deepEqual(sampleItem({ id: "1", name: "x" }), { id: "1", name: "x", createdAt: null, updatedAt: null, group: null, columnValues: [] });
});
test("rejects mutations and redacts tokens", () => { assert.throws(() => assertReadOnlyQuery("mutation { create_item }")); assert.doesNotThrow(() => assertReadOnlyQuery("query { boards { id } }")); assert.equal(redactToken("secret"), "[REDACTED]"); });
test("handles GraphQL errors and rate limits without leaking a token", async () => {
  const graphql = new MondayClient("secret", async () => new Response(JSON.stringify({ errors: [{ message: "bad query" }] }), { status: 200, headers: { "content-type": "application/json" } })); await assert.rejects(graphql.query("query { boards { id } }"), /bad query/);
  let attempts = 0; const limited = new MondayClient("secret", async () => { attempts += 1; return new Response("{}", { status: 429, headers: { "retry-after": "3" } }); }); await assert.rejects(limited.query("query { boards { id } }"), /rate limit.*3/i); assert.equal(attempts, 3);
});
test("paginates board items without loading an entire board at once", async () => {
  const seen: string[] = []; const client = new MondayClient("secret", async (_url, init) => { const body = JSON.parse(String(init?.body)); seen.push(body.query); const page = body.variables.cursor ? { data: { next_items_page: { cursor: null, items: [{ id: "2", name: "second" }] } } } : { data: { boards: [{ items_page: { cursor: "next", items: [{ id: "1", name: "first" }] } }] } }; return new Response(JSON.stringify(page), { headers: { "content-type": "application/json" } }); }); const result = await client.collectItems("9", 200); assert.equal(result.items.length, 2); assert.equal(seen.length, 2); assert.match(seen[0], /items_page\(limit/); assert.match(seen[1], /next_items_page/);
});
test("summarizes weekly leads separately from Sales Inbox and validates dates", () => {
  const item = (id: string, group: string, manager: string, channel: string, converted: string | null, date: string | null) => ({ id, name: `Lead ${id}`, group: { id: group, title: group }, column_values: [{ id: "people", text: manager, value: manager ? '{"personsAndTeams":[{"id":7,"kind":"person"}]}' : null }, { id: "status_16", text: channel }, { id: "status", text: converted }, { id: "date8", text: date }] });
  const summary = summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "WEEK 1", " Alice ", " Sales Inbox ", "Yes", "2026-07-02"), item("2", "WEEK 2", "Alice", "Personal", "will order in a while", "2026-07-03"), item("3", "WEEK 3", "", "sales inbox", null, "2026-06-30"), item("4", "Profit Tracking", "Bob", "sales inbox", "Yes", "2026-07-04"), item("5", "WEEK 4", "Bob, Carol", "SALES INBOX", "No", null)]);
  const all = summary.scopes.allLeads.byBoardMembership; const inbox = summary.scopes.salesInboxOnly.byBoardMembership;
  assert.deepEqual([all.totalLeadItems, all.convertedItems, all.conversionRate], [4, 1, 25]); assert.deepEqual([inbox.totalLeadItems, inbox.convertedItems, inbox.conversionRate], [3, 1, 33.3]); assert.equal(all.blankAccountManagerCount, 1); assert.equal(all.byChannel.find((row) => row.displayLabel === "Sales Inbox")?.leads, 3); assert.equal(summary.excludedItems[0].reason, "profit-tracking-group"); assert.equal(summary.validation.mismatchedDateCount, 1); assert.equal(summary.validation.missingDateCount, 1); assert.equal(summary.validation.multiManagerItemCount, 1); assert.equal(summary.scopes.allLeads.byValidDateInTouchMonth.totalLeadItems, 2);
  assert.deepEqual(summary, summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "WEEK 1", " Alice ", " Sales Inbox ", "Yes", "2026-07-02"), item("2", "WEEK 2", "Alice", "Personal", "will order in a while", "2026-07-03"), item("3", "WEEK 3", "", "sales inbox", null, "2026-06-30"), item("4", "Profit Tracking", "Bob", "sales inbox", "Yes", "2026-07-04"), item("5", "WEEK 4", "Bob, Carol", "SALES INBOX", "No", null)]));
});
test("keeps multi-manager rows in company and channel totals but excludes them from member metrics", () => {
  const item = (id: string, manager: string, channel: string, converted: string) => ({ id, name: id === "2" ? "Torus" : `Lead ${id}`, group: { id: "week", title: "WEEK 1" }, column_values: [{ id: "people", text: manager, value: '{"personsAndTeams":[{"id":1,"kind":"person"},{"id":2,"kind":"person"}]}' }, { id: "status_16", text: channel }, { id: "status", text: converted }, { id: "date8", text: "2026-07-01" }] });
  const summary = summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "Alice", "sales inbox", "No"), item("2", "hardus, Justin du Preez", "personal", "Yes"), item("3", "hardus, Justin du Preez", "sales inbox", "No")]); const company = summary.scopes.allLeads.byBoardMembership;
  assert.deepEqual([company.totalLeadItems, company.convertedItems, company.conversionRate], [3, 1, 33.3]); assert.deepEqual(company.byChannel.map((row) => [row.displayLabel, row.leads, row.converted]), [["personal", 1, 1], ["sales inbox", 2, 0]]); assert.deepEqual(company.byAccountManager.map((row) => [row.displayName, row.leads, row.converted]), [["Alice", 1, 0]]); assert.equal(company.byAccountManager.some((row) => row.displayName === "hardus" || row.displayName === "Justin du Preez"), false); assert.deepEqual(summary.validation.multiManagerItemCount, 2); assert.deepEqual(summary.validation.multiManagerConvertedCount, 1); assert.deepEqual(summary.validation.excludedFromMemberMetricsCount, 2); assert.equal(summary.multiAccountManagers.length, 2);
});
test("discovers case-insensitive monthly board names, duplicates, missing months, and structural changes", () => {
  const board = (id: string, name: string, changed = false) => ({ id, name, state: "active", groups: [1, 2, 3, 4].map((week) => ({ id: String(week), title: `WEEK ${week}` })), columns: [{ id: "people", title: "Acc Manager", type: "people" }, { id: changed ? "wrong" : "status_16", title: "Channel", type: "status", settings_str: '{"labels":{"1":"sales inbox"}}' }, { id: "date8", title: "Date In Touch", type: "date" }, { id: "status", title: "Converted", type: "status", settings_str: '{"labels":{"1":"Yes"}}' }] });
  assert.deepEqual(parseMonthlyBoardName(" january 2026 "), { year: 2026, month: 1, normalizedName: "JANUARY 2026" }); assert.equal(parseMonthlyBoardName("January sales 2026"), null); assert.equal(validateMonthlyBoard(board("1", "JANUARY 2026", true)).valid, true);
  const indexed = indexMonthlyBoards([board("1", "january 2026"), board("2", "FEBRUARY 2026"), board("3", "February 2026"), { ...board("4", "MARCH 2026"), board_kind: "subitems" }], 2026, new Date("2026-07-21T00:00:00Z")); assert.equal(indexed.index[0].status, "ready"); assert.equal(indexed.index[1].status, "ready"); assert.equal(indexed.duplicateMonths[0].rejectedCandidates.length, 1); assert.ok(indexed.missingMonths.includes(3)); assert.equal(classifyBoardPeriod(2026, 7, "active", new Date("2026-07-21T00:00:00Z")), "current active month");
});
test("aggregates annual rates from totals and groups members by Monday ID", () => {
  const metric = (leads: number, converted: number, name: string, id: string) => ({ totalLeadItems: leads, convertedItems: converted, conversionRate: 0, byAccountManager: [{ displayName: name, mondayUserIds: [id], leads, converted }], byChannel: [{ displayLabel: "sales inbox", leads, converted }], blankChannelCount: 0, blankAccountManagerCount: 0 });
  const result = aggregateYear([{ month: 1, boardId: "a", summary: { scopes: { allLeads: { byBoardMembership: metric(10, 1, "Alice", "7") }, salesInboxOnly: { byBoardMembership: metric(5, 1, "Alice", "7") } }, validation: { multiManagerItemCount: 1 } } }, { month: 2, boardId: "b", summary: { scopes: { allLeads: { byBoardMembership: metric(1, 1, "ALICE SMITH", "7") }, salesInboxOnly: { byBoardMembership: metric(1, 1, "ALICE SMITH", "7") } }, validation: { multiManagerItemCount: 2 } } }]);
  assert.deepEqual([result.company.leads, result.company.converted, result.company.conversionRate], [11, 2, 18.2]); assert.equal(result.members.length, 1); assert.deepEqual(result.members[0].observedDisplayNames, ["Alice", "ALICE SMITH"]); assert.equal(result.validation.multiManagerItemCount, 3);
});
test("accepts consolidated historical weeks and selects the weekly board over a title-case alternate", () => {
  const columns = [{ id: "new_people", title: "ACC Manager", type: "people" }, { id: "new_channel", title: "channel", type: "status", settings_str: '{"labels":{"1":"Sales Inbox"}}' }, { id: "new_date", title: "DATE IN TOUCH", type: "date" }, { id: "new_converted", title: "converted", type: "status", settings_str: '{"labels":{"1":"YES"}}' }];
  const weekly = { id: "18420001220", name: "JULY 2026", state: "active", workspace: { id: "1", name: "Pins & Knuckles UK" }, groups: [{ id: "week", title: "WEEK 1" }, { id: "profit", title: "Profit Tracking" }], columns }; const alternate = { ...weekly, id: "alt", name: "July 2026", groups: [{ id: "sales", title: "July Sales" }] };
  const validation = validateMonthlyBoard(weekly); assert.equal(validation.valid, true); assert.ok(validation.warnings.some((issue) => issue.code === "MISSING_WEEK_GROUP")); assert.deepEqual(validation.resolvedColumns, { people: "new_people", channel: "new_channel", dateInTouch: "new_date", converted: "new_converted" }); assert.equal(validateMonthlyBoard(alternate).valid, false);
  const indexed = indexMonthlyBoards([weekly, alternate], 2026, new Date("2026-07-21T00:00:00Z")); assert.equal(indexed.index[6].board?.id, "18420001220"); assert.match(indexed.duplicateMonths[0].rejectedCandidates[0].reason, /weekly-schema/); assert.deepEqual(indexed.futureMonths, [8, 9, 10, 11, 12]);
});
test("keeps Date In Touch mismatches in board totals and emits deterministic review metadata", () => {
  const item = (id: string, date: string) => ({ id, name: `Lead ${id}`, group: { id: "week", title: "WEEK 1" }, column_values: [{ id: "people", text: "Alice", value: '{"personsAndTeams":[{"id":7,"kind":"person"}]}' }, { id: "status_16", text: "sales inbox" }, { id: "status", text: "Yes" }, { id: "date8", text: date }] });
  const summary = summarizeMonthlySalesBoard({ id: "feb", name: "FEBRUARY 2026" }, [item("previous", "2026-01-05"), item("next", "2026-03-01"), item("valid", "2026-02-01")]); const all = summary.scopes.allLeads;
  assert.deepEqual([all.byBoardMembership.totalLeadItems, all.byBoardMembership.convertedItems], [3, 3]); assert.deepEqual([all.byValidDateInTouchMonth.totalLeadItems, all.byValidDateInTouchMonth.convertedItems], [1, 1]); assert.deepEqual(summary.mismatchedDates, [{ sourceBoardId: "feb", sourceBoardMonth: "FEBRUARY 2026", itemId: "previous", itemName: "Lead previous", group: "WEEK 1", actualDateInTouch: "2026-01-05", includedInBoardMembershipTotals: true, includedInValidDateTotals: false, action: "review-in-monday" }, { sourceBoardId: "feb", sourceBoardMonth: "FEBRUARY 2026", itemId: "next", itemName: "Lead next", group: "WEEK 1", actualDateInTouch: "2026-03-01", includedInBoardMembershipTotals: true, includedInValidDateTotals: false, action: "review-in-monday" }]);
  const annual = aggregateYear([{ month: 2, boardId: "feb", summary }]); assert.deepEqual([annual.company.leads, annual.company.converted], [3, 3]); assert.deepEqual(annual.mismatchedDates, summary.mismatchedDates);
});
