import assert from "node:assert/strict";
import test from "node:test";
import { MondayClient, assertReadOnlyQuery, dateCoverage, normalizeBoard, normalizePeople, normalizeStatus, parseMondayDate, redactToken, sampleItem, summarizeMonthlySalesBoard } from "../lib/monday/salesHistoryAudit.ts";

test("normalizes board, status, people, dates, and coverage deterministically", () => {
  assert.deepEqual(normalizeBoard({ id: "1", name: "Sales", state: "active", groups: [{ id: "g", title: "Inbox" }], columns: [{ id: "status", title: "Stage", type: "status" }], workspace: { id: "2", name: "Ops" } }).columns, [{ id: "status", title: "Stage", type: "status", settings: null }]);
  assert.equal(normalizeStatus(" Converted  "), "converted"); assert.deepEqual(normalizePeople('{"personsAndTeams":[{"id":12,"kind":"person"},{"id":99,"kind":"team"}]}'), [{ id: "12", name: "" }]); assert.equal(parseMondayDate("2024-02-03"), "2024-02-03");
  assert.deepEqual(dateCoverage([{ id: "1", name: "a", created_at: "2024-03-01" }, { id: "2", name: "b", created_at: null }]), { earliestUsableItemDate: "2024-03-01", latestUsableItemDate: "2024-03-01", datedItemCount: 1, undatedItemCount: 1 }); assert.deepEqual(sampleItem({ id: "1", name: "x" }), { id: "1", name: "x", createdAt: null, updatedAt: null, group: null, columnValues: [] });
});
test("rejects mutations and redacts tokens", () => { assert.throws(() => assertReadOnlyQuery("mutation { create_item }")); assert.doesNotThrow(() => assertReadOnlyQuery("query { boards { id } }")); assert.equal(redactToken("secret"), "[REDACTED]"); });
test("handles GraphQL errors and rate limits without leaking a token", async () => {
  const graphql = new MondayClient("secret", async () => new Response(JSON.stringify({ errors: [{ message: "bad query" }] }), { status: 200, headers: { "content-type": "application/json" } })); await assert.rejects(graphql.query("query { boards { id } }"), /bad query/);
  const limited = new MondayClient("secret", async () => new Response("{}", { status: 429, headers: { "retry-after": "3" } })); await assert.rejects(limited.query("query { boards { id } }"), /rate limit.*3/i);
});
test("paginates board items without loading an entire board at once", async () => {
  const seen: string[] = []; const client = new MondayClient("secret", async (_url, init) => { const body = JSON.parse(String(init?.body)); seen.push(body.query); const page = body.variables.cursor ? { data: { next_items_page: { cursor: null, items: [{ id: "2", name: "second" }] } } } : { data: { boards: [{ items_page: { cursor: "next", items: [{ id: "1", name: "first" }] } }] } }; return new Response(JSON.stringify(page), { headers: { "content-type": "application/json" } }); }); const result = await client.collectItems("9", 200); assert.equal(result.items.length, 2); assert.equal(seen.length, 2); assert.match(seen[0], /items_page\(limit/); assert.match(seen[1], /next_items_page/);
});
test("summarizes weekly leads separately from Sales Inbox and validates dates", () => {
  const item = (id: string, group: string, manager: string, channel: string, converted: string | null, date: string | null) => ({ id, name: `Lead ${id}`, group: { id: group, title: group }, column_values: [{ id: "people", text: manager, value: manager ? '{"personsAndTeams":[{"id":7,"kind":"person"}]}' : null }, { id: "status_16", text: channel }, { id: "status", text: converted }, { id: "date8", text: date }] });
  const summary = summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "WEEK 1", " Alice ", " Sales Inbox ", "Yes", "2026-07-02"), item("2", "WEEK 2", "Alice", "Personal", "will order in a while", "2026-07-03"), item("3", "WEEK 3", "", "sales inbox", null, "2026-06-30"), item("4", "Profit Tracking", "Bob", "sales inbox", "Yes", "2026-07-04"), item("5", "WEEK 4", "Bob, Carol", "SALES INBOX", "No", null)]);
  const all = summary.scopes.allLeads.byBoardMembership; const inbox = summary.scopes.salesInboxOnly.byBoardMembership;
  assert.deepEqual([all.totalLeadItems, all.convertedItems, all.conversionRate], [4, 1, 25]); assert.deepEqual([inbox.totalLeadItems, inbox.convertedItems, inbox.conversionRate], [3, 1, 33.3]); assert.equal(all.blankAccountManagerCount, 1); assert.equal(all.byChannel.find((row) => row.displayLabel === "Sales Inbox")?.leads, 3); assert.equal(summary.excludedItems[0].reason, "profit-tracking-group"); assert.equal(summary.validation.mismatchedDateCount, 1); assert.equal(summary.validation.missingDateCount, 1); assert.equal(summary.validation.multiManagerItemCount, 1); assert.equal(summary.scopes.allLeads.byValidDateInTouchMonth.totalLeadItems, 2);
  assert.deepEqual(summary, summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "WEEK 1", " Alice ", " Sales Inbox ", "Yes", "2026-07-02"), item("2", "WEEK 2", "Alice", "Personal", "will order in a while", "2026-07-03"), item("3", "WEEK 3", "", "sales inbox", null, "2026-06-30"), item("4", "Profit Tracking", "Bob", "sales inbox", "Yes", "2026-07-04"), item("5", "WEEK 4", "Bob, Carol", "SALES INBOX", "No", null)]));
});
test("keeps multi-manager rows in company and channel totals but excludes them from member metrics", () => {
  const item = (id: string, manager: string, channel: string, converted: string) => ({ id, name: id === "2" ? "Torus" : `Lead ${id}`, group: { id: "week", title: "WEEK 1" }, column_values: [{ id: "people", text: manager, value: '{"personsAndTeams":[{"id":1,"kind":"person"},{"id":2,"kind":"person"}]}' }, { id: "status_16", text: channel }, { id: "status", text: converted }, { id: "date8", text: "2026-07-01" }] });
  const summary = summarizeMonthlySalesBoard({ id: "1", name: "JULY 2026" }, [item("1", "Alice", "sales inbox", "No"), item("2", "hardus, Justin du Preez", "personal", "Yes"), item("3", "hardus, Justin du Preez", "sales inbox", "No")]); const company = summary.scopes.allLeads.byBoardMembership;
  assert.deepEqual([company.totalLeadItems, company.convertedItems, company.conversionRate], [3, 1, 33.3]); assert.deepEqual(company.byChannel.map((row) => [row.displayLabel, row.leads, row.converted]), [["personal", 1, 1], ["sales inbox", 2, 0]]); assert.deepEqual(company.byAccountManager.map((row) => [row.displayName, row.leads, row.converted]), [["Alice", 1, 0]]); assert.equal(company.byAccountManager.some((row) => row.displayName === "hardus" || row.displayName === "Justin du Preez"), false); assert.deepEqual(summary.validation.multiManagerItemCount, 2); assert.deepEqual(summary.validation.multiManagerConvertedCount, 1); assert.deepEqual(summary.validation.excludedFromMemberMetricsCount, 2); assert.equal(summary.multiAccountManagers.length, 2);
});
