import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { MondayClient, dateCoverage, normalizeBoard, sampleItem, summarizeMonthlySalesBoard, unresolvedMappingReport } from "./lib/monday/salesHistoryAudit.ts";

const output = "docs/imports/monday-sales-history";
function option(args: string[], name: string) { const index = args.indexOf(name); return index === -1 ? undefined : args[index + 1]; }
function boardId(args: string[]) { const id = option(args, "--board-id") ?? process.env.MONDAY_SALES_BOARD_ID ?? process.env.MONDAY_QUOTES_BOARD_ID ?? process.env.MONDAY_ORDERS_BOARD_ID; if (!id) throw new Error("--board-id is required (or set a MONDAY_*_BOARD_ID server-only variable)."); return id; }
function client() { return new MondayClient(process.env.MONDAY_API_TOKEN ?? ""); }
async function writeJson(name: string, value: unknown) { await mkdir(resolve(output), { recursive: true }); await writeFile(resolve(output, name), `${JSON.stringify(value, null, 2)}\n`); }
async function writeGenerated(boardId: string, name: string, value: unknown) { const directory = resolve(output, "generated", boardId); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), `${JSON.stringify(value, null, 2)}\n`); }
async function writeGeneratedText(boardId: string, name: string, value: string) { const directory = resolve(output, "generated", boardId); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), value); }
async function main() {
  const [command = "help", ...args] = process.argv.slice(2); const monday = client();
  if (command === "boards") { const boards = (await monday.listBoards()).map(normalizeBoard); console.log(JSON.stringify(boards, null, 2)); return; }
  const id = boardId(args); const board = await monday.inspectBoard(id); if (!board) throw new Error(`Board ${id} was not found or is not accessible.`);
  if (command === "inspect" || command === "columns") { console.log(JSON.stringify(normalizeBoard(board), null, 2)); return; }
  if (command === "summarize") { const collected = await monday.collectItems(id); const summary = summarizeMonthlySalesBoard(board, collected.items); const allLeads = summary.scopes.allLeads.byBoardMembership; const salesInbox = summary.scopes.salesInboxOnly.byBoardMembership; const reportDirectory = `generated/${id}`; await Promise.all([writeGenerated(id, "monthly-summary.json", summary), writeGenerated(id, "all-leads-by-member.json", allLeads.byAccountManager), writeGenerated(id, "sales-inbox-by-member.json", salesInbox.byAccountManager), writeGenerated(id, "channel-breakdown.json", allLeads.byChannel), writeGenerated(id, "validation-report.json", { validation: summary.validation, missingDates: summary.missingDates, mismatchedDates: summary.mismatchedDates, multiAccountManagers: summary.multiAccountManagers, dateScopeNote: "Board-membership totals include all WEEK 1–4 items. Valid-Date totals are supplied separately and do not silently discard mismatches." }), writeGenerated(id, "excluded-items.json", summary.excludedItems), writeGeneratedText(id, "README.md", `# ${board.name} monthly sales audit\n\nGenerated read-only from Monday board ${id}. Profit Tracking and non-weekly groups are excluded. Scope A counts all weekly lead items; Scope B counts only Channel = sales inbox (case-insensitive). Both board-membership and valid Date In Touch month totals are in monthly-summary.json. Multi-manager items stay in company and channel totals, but are excluded from member metrics without splitting or first-manager attribution; their rows remain in validation-report.json. Profit is excluded: EPCC emails remain authoritative.\n`) ]); console.log(JSON.stringify({ reportDirectory: `${output}/${reportDirectory}`, totalItemsFetched: summary.fetch.totalItemsFetched, includedWeeklyItems: summary.fetch.includedWeeklyItems, scopeA: allLeads, scopeB: salesInbox, validation: summary.validation }, null, 2)); return; }
  const limit = Math.max(1, Math.min(Number(option(args, "--limit") ?? 20), 2_000)); const collected = await monday.collectItems(id, limit);
  if (command === "sample") { console.log(JSON.stringify({ board: normalizeBoard(board), sampleItems: collected.items.map(sampleItem), paginationRequired: collected.truncated }, null, 2)); return; }
  const coverage = dateCoverage(collected.items, option(args, "--date-column-id"));
  if (command === "coverage") { console.log(JSON.stringify({ boardId: id, ...coverage, paginationRequired: collected.truncated, note: "Use --date-column-id only after mapping review; otherwise this uses created_at." }, null, 2)); return; }
  if (command === "report") { const normalized = normalizeBoard(board); const inventory = { ...normalized, sampledActiveItemCount: collected.items.length, activeItemCount: collected.truncated ? null : collected.items.length, archivedItemAvailability: "unverified: this audit does not assume archived items are accessible", paginationRequired: collected.truncated }; await Promise.all([writeJson("boards.json", [inventory]), writeJson(`column-map-${id}.json`, normalized), writeJson(`sample-items-${id}.json`, { boardId: id, items: collected.items.map(sampleItem), paginationRequired: collected.truncated }), writeJson(`date-coverage-${id}.json`, { boardId: id, ...coverage, paginationRequired: collected.truncated }), writeJson("unresolved-mapping-report.json", unresolvedMappingReport(board))]); console.log(`Wrote read-only discovery report to ${output}`); return; }
  throw new Error("Use boards, inspect, columns, sample, coverage, report, or summarize.");
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
