import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { MondayClient, dateCoverage, normalizeBoard, sampleItem, summarizeMonthlySalesBoard, unresolvedMappingReport } from "./lib/monday/salesHistoryAudit.ts";
import { aggregateYear, discoverMonthlyBoards } from "./lib/monday/monthlyBoardAudit.ts";

const output = "docs/imports/monday-sales-history";
function option(args: string[], name: string) { const index = args.indexOf(name); return index === -1 ? undefined : args[index + 1]; }
function year(args: string[]) { const value = Number(option(args, "--year")); if (!Number.isInteger(value) || value < 2020) throw new Error("--year must be a four-digit year."); return value; }
function boardId(args: string[]) { const id = option(args, "--board-id") ?? process.env.MONDAY_SALES_BOARD_ID ?? process.env.MONDAY_QUOTES_BOARD_ID ?? process.env.MONDAY_ORDERS_BOARD_ID; if (!id) throw new Error("--board-id is required (or set a MONDAY_*_BOARD_ID server-only variable)."); return id; }
function client() { return new MondayClient(process.env.MONDAY_API_TOKEN ?? ""); }
async function writeJson(name: string, value: unknown) { await mkdir(resolve(output), { recursive: true }); await writeFile(resolve(output, name), `${JSON.stringify(value, null, 2)}\n`); }
async function writeGenerated(boardId: string, name: string, value: unknown) { const directory = resolve(output, "generated", boardId); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), `${JSON.stringify(value, null, 2)}\n`); }
async function writeGeneratedText(boardId: string, name: string, value: string) { const directory = resolve(output, "generated", boardId); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), value); }
async function writeYear(yearValue: number, name: string, value: unknown) { const directory = resolve(output, "generated", String(yearValue)); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), `${JSON.stringify(value, null, 2)}\n`); }
async function writeYearText(yearValue: number, name: string, value: string) { const directory = resolve(output, "generated", String(yearValue)); await mkdir(directory, { recursive: true }); await writeFile(resolve(directory, name), value); }
async function discover(monday: MondayClient, yearValue: number) { return discoverMonthlyBoards(yearValue, await monday.listAllBoards(), (boardId) => monday.inspectBoard(boardId)); }
async function writeMonthly(boardIdValue: string, boardName: string, summary: ReturnType<typeof summarizeMonthlySalesBoard>) { const allLeads = summary.scopes.allLeads.byBoardMembership; const salesInbox = summary.scopes.salesInboxOnly.byBoardMembership; await Promise.all([writeGenerated(boardIdValue, "monthly-summary.json", summary), writeGenerated(boardIdValue, "all-leads-by-member.json", allLeads.byAccountManager), writeGenerated(boardIdValue, "sales-inbox-by-member.json", salesInbox.byAccountManager), writeGenerated(boardIdValue, "channel-breakdown.json", allLeads.byChannel), writeGenerated(boardIdValue, "validation-report.json", { validation: summary.validation, missingDates: summary.missingDates, mismatchedDates: summary.mismatchedDates, multiAccountManagers: summary.multiAccountManagers, dateScopeNote: "Board membership is authoritative for reporting. Date In Touch is a data-quality comparison only: mismatches remain in board totals, are excluded from valid-date comparison totals, and require review in Monday." }), writeGenerated(boardIdValue, "excluded-items.json", summary.excludedItems), writeGeneratedText(boardIdValue, "README.md", `# ${boardName} monthly sales audit\n\nBoard membership is the main reporting basis. Date In Touch is a data-quality check: mismatched rows remain in board totals, are not moved, and are listed for review in Monday. Profit Tracking and non-weekly groups are excluded. Multi-manager items remain in company and channel totals but are excluded from member metrics. Profit is excluded.\n`) ]); }
async function main() {
  const [command = "help", ...args] = process.argv.slice(2); const monday = client();
  if (command === "boards") { const boards = (await monday.listBoards()).map(normalizeBoard); console.log(JSON.stringify(boards, null, 2)); return; }
  if (command === "discover-monthly-boards") { const yearValue = year(args); const result = await discover(monday, yearValue); const snapshot = { generatedAt: new Date().toISOString(), year: yearValue, ...result }; const destination = option(args, "--output"); if (destination) { await mkdir(resolve(destination), { recursive: true }); await writeFile(resolve(destination, "monthly-board-index.json"), `${JSON.stringify(snapshot, null, 2)}\n`); } else await writeYear(yearValue, "monthly-board-index.json", snapshot); console.log(JSON.stringify(snapshot, null, 2)); return; }
  if (command === "summary-year") { const yearValue = year(args); const discovered = await discover(monday, yearValue); const statuses = discovered.index.map((entry) => ({ month: entry.month, monthName: entry.monthName, status: entry.status, boardId: entry.board ? String(entry.board.id) : null, boardName: entry.board?.name ?? null, periodStatus: entry.periodStatus ?? null, issues: entry.structure?.issues ?? [] })); const completed: Array<{ month: number; boardId: string; summary: ReturnType<typeof summarizeMonthlySalesBoard> }> = [];
    for (const entry of discovered.index) { const board = entry.board; if (entry.status !== "ready" || !board) continue; try { const collected = await monday.collectItems(String(board.id)); const summary = summarizeMonthlySalesBoard(board, collected.items, entry.structure?.resolvedColumns); await writeMonthly(String(board.id), board.name, summary); completed.push({ month: entry.month, boardId: String(board.id), summary }); const status = statuses.find((item) => item.month === entry.month); if (status) status.status = "summarized"; } catch (error) { const status = statuses.find((item) => item.month === entry.month); if (status) { status.status = "API failure"; status.issues = [{ code: "API_FAILURE", message: error instanceof Error ? error.message : "Unknown error" }]; } } }
    const annual = aggregateYear(completed); const validation = { generatedAt: new Date().toISOString(), year: yearValue, monthlyStatuses: statuses, annualValidation: annual.validation, mismatchedDates: annual.mismatchedDates, identityConflicts: annual.identityConflicts, currentMonthWarning: statuses.filter((entry) => entry.periodStatus === "current active month").map((entry) => entry.month) }; await Promise.all([writeYear(yearValue, "year-summary.json", { generatedAt: new Date().toISOString(), year: yearValue, reportingBasis: "board-membership", annual, validation: { ...annual.validation, mismatchedDates: annual.mismatchedDates }, monthlyStatuses: statuses }), writeYear(yearValue, "monthly-board-index.json", { generatedAt: new Date().toISOString(), year: yearValue, ...discovered }), writeYear(yearValue, "validation-report.json", validation), writeYear(yearValue, "missing-months.json", discovered.missingMonths), writeYear(yearValue, "duplicate-months.json", discovered.duplicateMonths), writeYear(yearValue, "member-year-summary.json", annual.members), writeYear(yearValue, "channel-year-summary.json", annual.channels), writeYear(yearValue, "sales-inbox-year-summary.json", annual.salesInbox), writeYearText(yearValue, "README.md", `# ${yearValue} Monday Sales history audit\n\nBoard membership is the main reporting basis. Date In Touch is a data-quality check: mismatched rows remain in board totals, are not moved, and are listed for review in Monday. Months marked current active month are not final historical data. Profit is out of scope.\n`) ]); console.log(JSON.stringify({ year: yearValue, annual, monthlyStatuses: statuses }, null, 2)); return; }
  const id = boardId(args); const board = await monday.inspectBoard(id); if (!board) throw new Error(`Board ${id} was not found or is not accessible.`);
  if (command === "inspect" || command === "columns") { console.log(JSON.stringify(normalizeBoard(board), null, 2)); return; }
  if (command === "summarize") { const collected = await monday.collectItems(id); const summary = summarizeMonthlySalesBoard(board, collected.items); const allLeads = summary.scopes.allLeads.byBoardMembership; const salesInbox = summary.scopes.salesInboxOnly.byBoardMembership; const reportDirectory = `generated/${id}`; await writeMonthly(id, board.name, summary); console.log(JSON.stringify({ reportDirectory: `${output}/${reportDirectory}`, reportingBasis: "board-membership", totalItemsFetched: summary.fetch.totalItemsFetched, includedWeeklyItems: summary.fetch.includedWeeklyItems, scopeA: allLeads, scopeB: salesInbox, validation: summary.validation }, null, 2)); return; }
  const limit = Math.max(1, Math.min(Number(option(args, "--limit") ?? 20), 2_000)); const collected = await monday.collectItems(id, limit);
  if (command === "sample") { console.log(JSON.stringify({ board: normalizeBoard(board), sampleItems: collected.items.map(sampleItem), paginationRequired: collected.truncated }, null, 2)); return; }
  const coverage = dateCoverage(collected.items, option(args, "--date-column-id"));
  if (command === "coverage") { console.log(JSON.stringify({ boardId: id, ...coverage, paginationRequired: collected.truncated, note: "Use --date-column-id only after mapping review; otherwise this uses created_at." }, null, 2)); return; }
  if (command === "report") { const normalized = normalizeBoard(board); const inventory = { ...normalized, sampledActiveItemCount: collected.items.length, activeItemCount: collected.truncated ? null : collected.items.length, archivedItemAvailability: "unverified: this audit does not assume archived items are accessible", paginationRequired: collected.truncated }; await Promise.all([writeJson("boards.json", [inventory]), writeJson(`column-map-${id}.json`, normalized), writeJson(`sample-items-${id}.json`, { boardId: id, items: collected.items.map(sampleItem), paginationRequired: collected.truncated }), writeJson(`date-coverage-${id}.json`, { boardId: id, ...coverage, paginationRequired: collected.truncated }), writeJson("unresolved-mapping-report.json", unresolvedMappingReport(board))]); console.log(`Wrote read-only discovery report to ${output}`); return; }
  throw new Error("Use boards, inspect, columns, sample, coverage, report, or summarize.");
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
