"use client";
import { useActionState, useEffect, useRef, useState } from "react";
import { inviteMember } from "../actions/inviteMember";
import { initialInviteActionState, allOrganisationRoles } from "../types";
import { pinsHubAccessLabels, pinsHubAccessLevels } from "@/lib/access/pinsHubRoles";
import { mondayIdentities } from "@/features/sales-dashboard/domain/memberIdentity";
import { feedback } from "@/components/ui/feedback";

export function emailDisplayName(email: string) { return email.split("@", 1)[0].replace(/[._-]+/g, " ").trim().replace(/\s+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
export function AddUserForm() {
  const [state, action, pending] = useActionState(inviteMember, initialInviteActionState); const [name, setName] = useState(""); const [nameTouched, setNameTouched] = useState(false); const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.status === "success" && state.message) feedback.success(state.message); if (state.status === "error" && state.message) feedback.error(state.message); }, [state]);
  function reset() { formRef.current?.reset(); setName(""); setNameTouched(false); }
  return <form ref={formRef} action={action} className="grid gap-3 rounded-lg border border-border bg-card/70 p-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Email address<input required name="email" type="email" maxLength={320} onChange={(event) => { if (!nameTouched) setName(emailDisplayName(event.target.value)); }} className="h-9 rounded-md bg-background px-2" /></label><label className="grid gap-1 text-sm">Display name<input required name="full_name" value={name} maxLength={200} onChange={(event) => { setNameTouched(true); setName(event.target.value); }} className="h-9 rounded-md bg-background px-2" /></label><label className="grid gap-1 text-sm">Organisation role<select name="organisation_role" defaultValue="admin" className="h-9 rounded-md border bg-background px-2">{allOrganisationRoles.map((role) => <option key={role} value={role}>{role[0].toUpperCase() + role.slice(1)}</option>)}</select></label><label className="grid gap-1 text-sm">Pins Hub access<select name="access_level" defaultValue="admin" className="h-9 rounded-md border bg-background px-2">{pinsHubAccessLevels.map((level) => <option key={level} value={level}>{pinsHubAccessLabels[level]}</option>)}</select></label><label className="grid gap-1 text-sm">Monday user mapping<select name="monday_member_id" defaultValue="none" className="h-9 rounded-md border bg-background px-2"><option value="none">Not linked</option>{mondayIdentities().map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label className="grid gap-1 text-sm">Optional invite message<textarea name="invite_message" maxLength={1000} className="min-h-20 rounded-md border bg-background p-2" /></label><div className="flex gap-2 sm:col-span-2"><button disabled={pending} className="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground">{pending ? "Adding…" : "Add User"}</button><button type="button" onClick={reset} className="h-9 rounded-md border px-3 text-sm">Clear</button></div></form>;
}
