"use client";

import { useActionState, useMemo, useState } from "react";
import { deleteGarment, saveGarment } from "../actions";
import { initialDataManagementActionState, type AccessLevel, type GarmentRecord, type ProductTypeRecord } from "../types";

const inputClass = "h-9 rounded-md border border-input bg-background px-2.5 text-sm text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring";
type SortKey = "code" | "brand" | "name" | "productTypeName";
const display = (value: string | number | null) => value ?? "—";

export function GarmentsManager({ garments, productTypes, accessLevel }: { garments: GarmentRecord[]; productTypes: ProductTypeRecord[]; accessLevel: AccessLevel }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState<SortKey>("code"); const [selected, setSelected] = useState<GarmentRecord | null>(null); const canWrite = accessLevel !== "read";
  const visible = useMemo(() => garments.filter((item) => [item.code, item.altCode, item.brand, item.name, item.colour, item.tags, item.productTypeName].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase())).sort((left, right) => (left[sort] ?? "").localeCompare(right[sort] ?? "")), [garments, query, sort]);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><input aria-label="Search garments" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search garments" className={`${inputClass} w-full sm:w-72`} />{canWrite ? <button type="button" onClick={() => setSelected({ id: "", code: "", altCode: null, brand: null, name: "", colour: null, tags: null, eurBasePrice: null, gbpPrice: null, extraSizeCost: null, isActive: true, productTypeId: null, productTypeName: null })} className="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90">Add Garment</button> : null}</div>
    {selected ? <GarmentForm record={selected.id ? selected : null} productTypes={productTypes} accessLevel={accessLevel} onClose={() => setSelected(null)} /> : null}
    <div className="overflow-x-auto rounded-lg border border-border bg-card/70"><table className="min-w-[1050px] text-left text-sm"><thead className="bg-secondary/60 text-xs text-muted-foreground"><tr><th className="px-4 py-3">Edit</th><Header label="Code" active={sort === "code"} onClick={() => setSort("code")} /><th className="px-4 py-3">Alt Code</th><Header label="Brand" active={sort === "brand"} onClick={() => setSort("brand")} /><Header label="Name" active={sort === "name"} onClick={() => setSort("name")} /><th className="px-4 py-3">Colour</th><th className="px-4 py-3">Tags</th><th className="px-4 py-3">EUR Price</th><th className="px-4 py-3">GBP Price</th><th className="px-4 py-3">Extra Size Cost</th><Header label="Product Type" active={sort === "productTypeName"} onClick={() => setSort("productTypeName")} /><th className="px-4 py-3">Status</th></tr></thead><tbody>{visible.length ? visible.map((item) => <tr key={item.id} className="border-t border-border/70"><td className="px-4 py-3">{canWrite ? <button type="button" onClick={() => setSelected(item)} className="text-primary hover:underline">Edit</button> : "—"}</td><td className="px-4 py-3 font-mono text-xs">{item.code}</td><td className="px-4 py-3">{display(item.altCode)}</td><td className="px-4 py-3">{display(item.brand)}</td><td className="px-4 py-3 font-medium">{item.name}</td><td className="px-4 py-3">{display(item.colour)}</td><td className="max-w-48 truncate px-4 py-3">{display(item.tags)}</td><td className="px-4 py-3">{display(item.eurBasePrice)}</td><td className="px-4 py-3">{display(item.gbpPrice)}</td><td className="px-4 py-3">{display(item.extraSizeCost)}</td><td className="px-4 py-3">{display(item.productTypeName)}</td><td className="px-4 py-3">{item.isActive ? "Active" : "Inactive"}</td></tr>) : <tr><td colSpan={12} className="px-4 py-10 text-center text-muted-foreground">No garments.</td></tr>}</tbody></table></div>
  </div>;
}

function Header({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <th className="px-4 py-3"><button type="button" onClick={onClick} className={active ? "text-foreground" : "hover:text-foreground"}>{label}</button></th>; }
function GarmentForm({ record, productTypes, accessLevel, onClose }: { record: GarmentRecord | null; productTypes: ProductTypeRecord[]; accessLevel: AccessLevel; onClose: () => void }) { const [saveState, saveAction, pending] = useActionState(saveGarment, initialDataManagementActionState); const activeTypes = productTypes.filter((item) => item.isActive); return <div className="rounded-lg border border-border bg-card/80 p-4"><form action={saveAction} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input name="id" value={record?.id ?? ""} readOnly hidden />
  <Field label="Code" name="code" required defaultValue={record?.code ?? ""} /><Field label="Alt Code" name="alt_code" defaultValue={record?.altCode ?? ""} /><Field label="Brand" name="brand_name" defaultValue={record?.brand ?? ""} /><Field label="Name" name="name" required defaultValue={record?.name ?? ""} /><Field label="Colour" name="colour" defaultValue={record?.colour ?? ""} /><label className="grid gap-1 text-sm"><span>Product Type</span><select required name="product_type_id" defaultValue={record?.productTypeId ?? ""} className={inputClass}><option value="">Select Product Type</option>{activeTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Tags" name="tags" defaultValue={record?.tags ?? ""} /><label className="grid gap-1 text-sm"><span>Active</span><select name="is_active" defaultValue={record?.isActive === false ? "false" : "true"} className={inputClass}><option value="true">Active</option><option value="false">Inactive</option></select></label><NumberField label="EUR Price" name="eur_base_price" value={record?.eurBasePrice} /><NumberField label="GBP Price" name="gbp_price" value={record?.gbpPrice} /><NumberField label="Extra Size Cost" name="extra_size_cost" value={record?.extraSizeCost} />
  {saveState.message ? <p role={saveState.ok ? "status" : "alert"} className={`sm:col-span-2 lg:col-span-4 text-sm ${saveState.ok ? "text-emerald-400" : "text-destructive"}`}>{saveState.message}</p> : null}<div className="flex gap-2 sm:col-span-2 lg:col-span-4"><button disabled={pending} className="h-9 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground disabled:opacity-50">{pending ? "Saving…" : "Save Garment"}</button><button type="button" onClick={onClose} className="h-9 rounded-md border border-input px-3 text-sm hover:bg-accent">Close</button></div></form>{record && accessLevel === "admin" ? <div className="mt-3"><DeleteGarment id={record.id} /></div> : null}</div>; }
function Field({ label, name, defaultValue, required = false }: { label: string; name: string; defaultValue: string; required?: boolean }) { return <label className="grid gap-1 text-sm"><span>{label}</span><input required={required} name={name} defaultValue={defaultValue} className={inputClass} /></label>; }
function NumberField({ label, name, value }: { label: string; name: string; value: number | null | undefined }) { return <label className="grid gap-1 text-sm"><span>{label}</span><input name={name} type="number" min="0" step="0.01" defaultValue={value ?? ""} className={inputClass} /></label>; }
function DeleteGarment({ id }: { id: string }) { const [state, action, pending] = useActionState(deleteGarment, initialDataManagementActionState); return <form action={action} onSubmit={(event) => { if (!window.confirm("Permanently delete this garment?")) event.preventDefault(); }}><input hidden name="id" value={id} readOnly /><button disabled={pending} className="h-9 rounded-md border border-destructive/60 px-3 text-sm text-destructive hover:bg-destructive/10 disabled:opacity-50">Delete</button>{state.message ? <span role={state.ok ? "status" : "alert"} className="ml-2 text-sm text-destructive">{state.message}</span> : null}</form>; }
