import { MONTHLY_SALES_COLUMNS, normalizeStatus, type MondayBoard } from "./salesHistoryAudit.ts";

const months = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"];
type Issue = { code: string; message: string };
type Metric = { totalLeadItems: number; convertedItems: number; conversionRate: number; byAccountManager: Array<{ displayName: string; mondayUserIds: string[]; leads: number; converted: number }>; byChannel: Array<{ displayLabel: string; leads: number; converted: number }>; blankChannelCount: number; blankAccountManagerCount: number };

export function parseMonthlyBoardName(name: string) { const match = name.trim().match(/^(january|february|march|april|may|june|july|august|september|october|november|december)\s+(\d{4})$/i); if (!match) return null; const month = months.indexOf(match[1].toUpperCase()) + 1; return { year: Number(match[2]), month, normalizedName: `${months[month - 1]} ${match[2]}` }; }
function labels(settings: string | null | undefined) { try { return Object.values((JSON.parse(settings ?? "{}") as { labels?: Record<string, string> }).labels ?? {}).map((label) => normalizeStatus(label)); } catch { return []; } }
export function resolveMonthlyColumns(board: MondayBoard) {
  const columns = board.columns ?? []; const fields = [{ key: "people", legacyId: MONTHLY_SALES_COLUMNS.people, titles: ["acc manager", "account manager"], type: "people" }, { key: "channel", legacyId: MONTHLY_SALES_COLUMNS.channel, titles: ["channel", "lead channel"], type: "status" }, { key: "dateInTouch", legacyId: MONTHLY_SALES_COLUMNS.dateInTouch, titles: ["date in touch", "contact date"], type: "date" }, { key: "converted", legacyId: MONTHLY_SALES_COLUMNS.converted, titles: ["converted", "conversion"], type: "status" }] as const; const resolved: Record<string, string> = {}; const issues: Issue[] = [];
  for (const field of fields) { const semantic = columns.find((column) => field.titles.includes(normalizeStatus(column.title) as never) && column.type === field.type); const selected = semantic; if (!selected) { issues.push({ code: "MISSING_COLUMN", message: `Missing ${field.titles.join(" or ")} (${field.type}).` }); continue; } resolved[field.key] = selected.id; if (selected.id !== field.legacyId) issues.push({ code: "CHANGED_COLUMN_ID", message: `${field.titles[0]} resolved to ${selected.id}, not legacy ${field.legacyId}.` }); }
  return { resolved: resolved as typeof MONTHLY_SALES_COLUMNS, issues };
}
export function validateMonthlyBoard(board: MondayBoard) {
  const blocking: Issue[] = []; const warnings: Issue[] = []; const groups = (board.groups ?? []).map((group) => normalizeStatus(group.title)); const weekly = groups.filter((group) => /^week [1-5]$/.test(group)); const resolved = resolveMonthlyColumns(board); if (!weekly.length) blocking.push({ code: "NO_WEEK_GROUPS", message: "No WEEK 1–WEEK 5 group exists." }); for (const group of ["week 1", "week 2", "week 3", "week 4"]) if (!groups.includes(group)) warnings.push({ code: "MISSING_WEEK_GROUP", message: `Missing ${group}; historical groups may be consolidated.` }); for (const group of groups.filter((group) => group.startsWith("week ") && !/^week [1-5]$/.test(group))) warnings.push({ code: "UNEXPECTED_WEEK_GROUP", message: `Unexpected week group ${group}.` }); blocking.push(...resolved.issues.filter((issue) => issue.code === "MISSING_COLUMN")); warnings.push(...resolved.issues.filter((issue) => issue.code !== "MISSING_COLUMN")); const channel = (board.columns ?? []).find((column) => column.id === resolved.resolved.channel); const converted = (board.columns ?? []).find((column) => column.id === resolved.resolved.converted); if (!labels(channel?.settings_str).includes("sales inbox")) blocking.push({ code: "MISSING_SALES_INBOX_LABEL", message: "Channel does not expose sales inbox." }); if (!labels(converted?.settings_str).includes("yes")) blocking.push({ code: "MISSING_CONVERTED_YES_LABEL", message: "Converted does not expose Yes." }); return { valid: blocking.length === 0, issues: [...blocking, ...warnings], blocking, warnings, resolvedColumns: resolved.resolved, weeklyGroupCount: weekly.length };
}
export function classifyBoardPeriod(year: number, month: number, state: string | null | undefined, now = new Date()) { if (normalizeStatus(state) === "archived") return "archived"; const currentYear = now.getUTCFullYear(); const currentMonth = now.getUTCMonth() + 1; if (year > currentYear || (year === currentYear && month > currentMonth)) return "future month"; if (year === currentYear && month === currentMonth) return "current active month"; if (year < currentYear || month < currentMonth) return "complete/historical"; return "unknown"; }
export function indexMonthlyBoards(boards: MondayBoard[], year: number, now = new Date()) {
  const candidates = boards.map((board) => ({ board, parsed: parseMonthlyBoardName(board.name), structure: validateMonthlyBoard(board) })).filter((entry) => entry.parsed?.year === year && entry.board.board_kind !== "subitems"); const byMonth = new Map<number, typeof candidates>(); for (const candidate of candidates) { const list = byMonth.get(candidate.parsed!.month) ?? []; list.push(candidate); byMonth.set(candidate.parsed!.month, list); }
  const index = months.map((monthName, position) => { const month = position + 1; const periodStatus = classifyBoardPeriod(year, month, null, now); const entries = byMonth.get(month) ?? []; if (!entries.length) return { month, monthName, status: periodStatus === "future month" ? "future" : "missing", boards: [] as unknown[], periodStatus }; const score = (entry: typeof entries[number]) => (entry.structure.weeklyGroupCount ? 100 : 0) + (entry.structure.valid ? 40 : 0) + (normalizeStatus(entry.board.workspace?.name) === "pins & knuckles uk" ? 10 : 0) + (entry.board.name === entry.parsed!.normalizedName ? 1 : 0); const ordered = [...entries].sort((a, b) => score(b) - score(a) || String(a.board.id).localeCompare(String(b.board.id))); const selected = ordered[0]; const rejected = ordered.slice(1).map((entry) => ({ board: entry.board, schemaScore: score(entry), reason: "Rejected by deterministic weekly-schema preference." })); const status = selected.structure.valid ? "ready" : "structurally invalid"; return { month, monthName, status, board: selected.board, structure: selected.structure, schemaScore: score(selected), rejectedCandidates: rejected, periodStatus }; });
  return { index, missingMonths: index.filter((entry) => entry.status === "missing").map((entry) => entry.month), futureMonths: index.filter((entry) => entry.status === "future").map((entry) => entry.month), duplicateMonths: index.filter((entry) => (entry.rejectedCandidates?.length ?? 0) > 0).map((entry) => ({ month: entry.month, selectedBoard: entry.board, rejectedCandidates: entry.rejectedCandidates ?? [] })) };
}

export async function discoverMonthlyBoards(
  year: number,
  listedBoards: MondayBoard[],
  inspectBoard: (boardId: string) => Promise<MondayBoard | undefined>,
  now = new Date(),
) {
  const candidates = listedBoards.filter((board) => parseMonthlyBoardName(board.name)?.year === year && board.board_kind !== "subitems");
  const detailed = (await Promise.all(candidates.map((board) => inspectBoard(String(board.id))))).filter((board): board is MondayBoard => Boolean(board));
  return indexMonthlyBoards(detailed, year, now);
}
function metric(leads: number, converted: number) { return { leads, converted, conversionRate: leads ? Math.round((converted / leads) * 1000) / 10 : 0 }; }
export function aggregateYear(monthsToAggregate: Array<{ month: number; boardId: string; summary: { scopes: { allLeads: { byBoardMembership: Metric }; salesInboxOnly: { byBoardMembership: Metric } }; validation: Record<string, number>; mismatchedDates?: Array<Record<string, unknown>> } }>) {
  const company = { leads: 0, converted: 0 }; const inbox = { leads: 0, converted: 0 }; const member = new Map<string, { ids: string[]; names: Map<string, number>; leads: number; converted: number; monthly: Array<{ month: number; leads: number; converted: number }> }>(); const channel = new Map<string, { name: string; leads: number; converted: number; monthly: Array<{ month: number; leads: number; converted: number }> }>(); const validation: Record<string, number> = {}; const mismatchedDates: Array<Record<string, unknown>> = [];
  for (const entry of monthsToAggregate) { const all = entry.summary.scopes.allLeads.byBoardMembership; const salesInbox = entry.summary.scopes.salesInboxOnly.byBoardMembership; company.leads += all.totalLeadItems; company.converted += all.convertedItems; inbox.leads += salesInbox.totalLeadItems; inbox.converted += salesInbox.convertedItems; mismatchedDates.push(...(entry.summary.mismatchedDates ?? [])); for (const [key, value] of Object.entries(entry.summary.validation)) validation[key] = (validation[key] ?? 0) + value;
    for (const row of all.byAccountManager) { const id = row.mondayUserIds.length === 1 ? row.mondayUserIds[0] : `unresolved:${normalizeStatus(row.displayName)}`; const current = member.get(id) ?? { ids: row.mondayUserIds, names: new Map<string, number>(), leads: 0, converted: 0, monthly: [] as Array<{ month: number; leads: number; converted: number }> }; current.names.set(row.displayName, (current.names.get(row.displayName) ?? 0) + 1); current.leads += row.leads; current.converted += row.converted; current.monthly.push({ month: entry.month, leads: row.leads, converted: row.converted }); member.set(id, current); }
    for (const row of all.byChannel) { const key = normalizeStatus(row.displayLabel); const current = channel.get(key) ?? { name: row.displayLabel, leads: 0, converted: 0, monthly: [] as Array<{ month: number; leads: number; converted: number }> }; current.leads += row.leads; current.converted += row.converted; current.monthly.push({ month: entry.month, leads: row.leads, converted: row.converted }); channel.set(key, current); }
  }
  const memberRows = [...member.entries()].map(([identity, row]) => { const names = [...row.names.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])); return { identity, mondayUserIds: row.ids, canonicalDisplayName: names[0]?.[0] ?? "Unresolved", observedDisplayNames: names.map(([name]) => name), ...metric(row.leads, row.converted), monthly: row.monthly.sort((a, b) => a.month - b.month) }; }).sort((a, b) => a.canonicalDisplayName.localeCompare(b.canonicalDisplayName)); const conflicts = memberRows.filter((row) => row.identity.startsWith("unresolved:")).map((row) => ({ type: "NAME_WITHOUT_STABLE_ID", name: row.canonicalDisplayName }));
  return { company: { ...metric(company.leads, company.converted), monthly: monthsToAggregate.map((entry) => ({ month: entry.month, boardId: entry.boardId, ...metric(entry.summary.scopes.allLeads.byBoardMembership.totalLeadItems, entry.summary.scopes.allLeads.byBoardMembership.convertedItems) })) }, salesInbox: { ...metric(inbox.leads, inbox.converted), monthly: monthsToAggregate.map((entry) => ({ month: entry.month, boardId: entry.boardId, ...metric(entry.summary.scopes.salesInboxOnly.byBoardMembership.totalLeadItems, entry.summary.scopes.salesInboxOnly.byBoardMembership.convertedItems) })) }, members: memberRows, channels: [...channel.values()].map((row) => ({ channel: row.name, ...metric(row.leads, row.converted), monthly: row.monthly.sort((a, b) => a.month - b.month) })).sort((a, b) => a.channel.localeCompare(b.channel)), validation, mismatchedDates, identityConflicts: conflicts };
}
